### ISSUE TITLE
Support for firmware GBC-OS-v1.05 29.12.2021

### ISSUE THREAD

**Issue by cutrus** [orangeglo/everdrive-gb-editor#2]
Hey,

On December 29, a new software version 1.05 was released. Are you planning to add support for it?

https://krikzz.com/pub/support/everdrive-gb/x-series/OS/

**Comment by epbarger** [comment]
Just saw this, yes I will be adding support! Thanks for the notice

**Comment by epbarger** [comment]
Now updated for v1.05 as of https://github.com/orangeglo/everdrive-gb-editor/commit/98269ca0fc622d93859ea6d577bc94e07611ccaa
